### ISSUE TITLE
[Feat] 과제 3

### ISSUE THREAD

**Issue by chaentopia** [31st-IN-SOPT-iOS-Part/ChaeEunChung#6]
## 📝 To-do

- [ ] 친구 리스트 화면 구현
- [ ] 채팅 리스트 화면 구현
- [ ] 사진 선택 화면 구현
